include: package:pedantic/analysis_options.yaml

linter:
  rules:
    # If it's dynamic, then just say so
    avoid_annotating_with_dynamic: false

    # Types are good, so this rule sucks
    omit_local_variable_types: false

    # Great 95% of the time, but bad 5%
    always_specify_types: false

    # Awaiting futures in bloc `mapEventToState()` results in large performance decrease
    unawaited_futures: false

    # Constant constructors result in better performance
    prefer_const_constructors: true

    # Constant constructors result in better performance
    prefer_const_constructors_in_immutables: true

    # Unnecessary containers => longer build times
    avoid_unnecessary_containers: true

    # If a method is async, then it's return type should be Future<T>
    avoid_void_async: true

    # 
    avoid_unused_constructor_parameters: true

    sized_box_for_whitespace: true

    directives_ordering: true

    unnecessary_await_in_return: true

    always_put_required_named_parameters_first: true

    prefer_const_declarations: true

    prefer_const_literals_to_create_immutables: true

    unnecessary_const: false
