name: $(Rev:r:)

jobs:
  - job: Run_My_Pipeline
    timeoutInMinutes: 30
    pool:
      vmImage: macOS-latest

    steps:
      - script: |
        echo "install xcode in command line"
        xcode-select --install
        echo "install home brew"
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        echo "install flutter using brew"
        brew install --cask flutter
        echo "starting up apple emulator"
        flutter emulators --launch <apple_ios_simulator/android emulator>
        echo "awaiting for emualator to load"
        sleep 5
        echo "starting integration tests"
        flutter drive --target=test_driver/<yourtestfile>.dart
      displayName: Integration test IOS
