name: $(Rev:r:)

jobs:
  - job: Test
    pool:
      vmImage: macOS-latest

    steps:
      - task: FlutterInstall@0
        displayName: Setup flutter
        inputs:
          channel: stable
          version: latest

      - task: PowerShell@2
        displayName: Setup environment
      - script: |
          Write-Host "##vso[task.prependpath]$(JAVA_HOME_11_X64)"
          Write-Host "##vso[task.setvariable variable=JAVA_HOME;]$(JAVA_HOME_11_X64)"
          Write-Host "##vso[task.prependpath]$(FlutterToolPath)"
          Write-Host "##vso[task.prependpath]$(FlutterToolPath)/cache/dart-sdk/bin"

      - task: CmdLine@2
        displayName: Install packages
      - script: flutter pub get

      - task: CmdLine@2
        displayName: Run Unit Tests
      - script: |
          flutter test --machine > tests.output
          flutter test --coverage

      - task: CmdLine@2
        displayName: Setup Emulator
      - script: |
          $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-29;default;x86'
          $ANDROID_HOME/tools/bin/avdmanager create avd -n "pixel" --device "pixel" -k "system-images;android-29;default;x86"
          $ANDROID_HOME/emulator/emulator -avd "pixel" -no-snapshot &
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'

      - task: CmdLine@2
        displayName: Run Integration Tests
      - script: flutter drive --target=test_driver/app.dart
