name: $(Rev:r:)

jobs:
  - job: Run_My_Pipeline
    timeoutInMinutes: 30
    pool:
      vmImage: macOS-latest

    steps:
      - script: sudo chmod +x scripts/azure-pipelines.sh
        displayName: Grant Shell Permissions

      - script: scripts/azure-pipelines.sh install_flutter
        displayName: Install Flutter

      - script: scripts/azure-pipelines.sh run_unit_tests
        displayName: Run Unit Tests

      - script: scripts/azure-pipelines.sh install_emulator
        displayName: Install Emulator

      - script: scripts/azure-pipelines.sh run_emulator
        displayName: Run Emulator

      - script: scripts/azure-pipelines.sh run_integration_tests
        displayName: Run Integration Tests
