pool:
  vmImage: macOS-latest

steps:
  - script: |
      echo "Installing Flutter SDK"
      git clone -b stable https://github.com/flutter/flutter.git

      echo "Running flutter precache"
      flutter precache

      echo "Accepting android licenses"
      yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

      echo "Verifying Flutter installation"
      flutter doctor

      echo "Downloading Packages"
      flutter packages get
    displayName: Install Flutter

  - script: |
      echo "Running Unit Tests"
      flutter test --machine >tests.output
    displayName: Run Unit Tests

  - script: |
      echo "Installing Emulator SDK"
      $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-29;default;x86'

      echo "Creating Emulator"
      $ANDROID_HOME/tools/bin/avdmanager create avd -n "pixel" --device "pixel" -k "system-images;android-29;default;x86"

      echo "Starting Emulator"
      $ANDROID_HOME/emulator/emulator -avd "pixel" -no-snapshot &
      $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
      echo "Emulator started"
    displayName: Setup Emulator

  - script: |
      flutter drive --target=test_driver/app.dart
    displayName: Run Integration Tests
