variables:
  FlutterChannel: stable
  FlutterVersion: latest

jobs:
  - job: Test
    pool:
      vmImage: macOS-latest

    steps:
      - task: FlutterInstall@0
        displayName: Setup flutter
        inputs:
          channel: $(FlutterChannel)
          version: $(FlutterVersion)

      - task: PowerShell@2
        displayName: Setup environment
        inputs:
          targetType: inline
          script: |
            Write-Host "##vso[task.prependpath]$(JAVA_HOME_11_X64)"
            Write-Host "##vso[task.setvariable variable=JAVA_HOME;]$(JAVA_HOME_11_X64)"
            Write-Host "##vso[task.prependpath]$(FlutterToolPath)"
            Write-Host "##vso[task.prependpath]$(FlutterToolPath)/cache/dart-sdk/bin"

      - task: CmdLine@2
        displayName: Install packages
        inputs:
          script: flutter pub get

      - task: CmdLine@2
        displayName: Run Unit Tests
        inputs:
          script: |
            flutter test --machine > tests.output
            flutter test --coverage

      - task: CmdLine@2
        displayName: Setup Emulator
        inputs:
      - script: |
          $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-29;default;x86'
          $ANDROID_HOME/tools/bin/avdmanager create avd -n "pixel" --device "pixel" -k "system-images;android-29;default;x86"
          $ANDROID_HOME/emulator/emulator -avd "pixel" -no-snapshot &
          $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'

      - task: CmdLine@2
        displayName: Run Integration Tests
        inputs:
      - script: flutter drive --target=test_driver/app.dart
