name: lachies_life_planner
description: All-in-1 personal planner
version: 0.3.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: "1.0.1"
  firebase_core: "1.0.1"
  flutter_form_builder: "5.0.0"
  modal_bottom_sheet: "2.0.0"

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  cloud_firestore_mocks: "0.7.0"
  pedantic: "1.11.0"
  screenshots: "0.2.1"
  test: "1.16.5"

flutter:
  uses-material-design: true
