# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

  # speed up IOS build time - https://firebase.flutter.dev/docs/overview/#improve-ios-build-times
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '6.26.0'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

end
